trigger:
- develop

pool:
  name: Rideau

variables:
  project: 'E2E.Content.Management.UI'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Check/Install Node.js'

- task: Npm@1
  displayName: 'Install Npm Dependencies'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Update Npm Dependencies'
  inputs:
    command: update

- task: Npm@1
  displayName: 'Run Tests'
  inputs:
    command: custom
    customCommand: 'run test'

- task: Npm@1
  displayName: 'Build Project'
  inputs:
    command: custom
    customCommand: run build:prod

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist\forge-website'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(project).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(project)'
    publishLocation: 'Container'
