trigger:
- develop

pool:
  name: Local

variables:
  project: 'E2E.Loyalty.Forge.UI'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Check/Install Node.js'

- task: Npm@1
  displayName: 'Install Npm Dependencies'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Run Tests'
  inputs:
    command: custom
    customCommand: 'run test'
    
- task: Npm@1
  displayName: 'Build Project'
  inputs:
    command: custom
    customCommand: run build

- task: PublishPipelineArtifact@0
  displayName: 'Publish Artifact'
  inputs:
    artifactName: '$(project)'
    targetPath: 'dist'