name: $(MajorVersion).$(MinorVersion).$(PatchVersion).$(RevisionVersion)
trigger:
- develop

pool:
  name: Rideau

variables:
  MajorVersion: 1
  MinorVersion: 3
  PatchVersion: 0
  RevisionVersion: $[counter('revision-counter', 0)]
  project: 'E2E.Admin.UI'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Check/Install Node.js'

- task: Npm@1
  displayName: 'Install Npm Dependencies'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Update Npm Dependencies'
  inputs:
    command: custom
    customCommand: 'update'

- task: Npm@1
  displayName: 'Run Tests'
  inputs:
    command: custom
    customCommand: 'run test:ci'

- task: PublishTestResults@2
  displayName: "supply npm test test results to pipeline"
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-results.xml'

- task: Npm@1
  displayName: 'Build Project'
  inputs:
    command: custom
    customCommand: run build

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(project).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(project)'
    publishLocation: 'Container'
