trigger:
- develop

pool:
  name: Local

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Check/Install Node.js'

- task: Npm@1
  displayName: 'Install Npm Dependencies'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Run Tests'
  inputs:
    command: custom
    customCommand: 'run test --watch=false'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: './junit.xml'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
    failIfCoverageEmpty: true