name: $(MajorVersion).$(MinorVersion).$(PatchVersion).$(RevisionVersion)

# CI builds nightly
trigger:
- none

schedules:
- cron: '00 0 * * *'
  displayName: Every night at 00:00
  branches:
    include:
    - develop

pool:
  name: Rideau

variables:
  MajorVersion: 1
  MinorVersion: 2
  PatchVersion: 0
  RevisionVersion: $[counter('revision-counter', 0)]
  project: 'E2E.Admin.UI'

steps:
- task: SonarQubePrepare@4
  displayName: 'SonarQube Prepare'
  inputs:
    SonarQube: 'SonarQube-Rideau-PD'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(project)'
    cliProjectName: '$(project)'
    cliSources: '.'
    extraProperties: |
        sonar.sources=src
        sonar.exclusions=**/node_modules/**,src/assets/**,src/app/shared/components/dynamic-form/fields/field-content-editor/field-content-editor.component.ts,src/app/shared/components/dynamic-form/dynamic-form.component.ts
        sonar.tests=src
        sonar.test.inclusions=**/*.spec.ts;**/*.spec.js
        sonar.typescript.lcov.reportPaths=coverage/lcov.info
        sonar.branch.name=$(Build.SourceBranchName)

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Check/Install Node.js'

- task: Npm@1
  displayName: 'Install Npm Dependencies'
  inputs:
    command: install

- task: Npm@1
  displayName: 'Update Npm Dependencies'
  inputs:
    command: custom
    customCommand: 'update'

- task: Npm@1
  displayName: 'Run Tests'
  inputs:
    command: custom
    customCommand: 'run test'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/test-results.xml'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
    failIfCoverageEmpty: true

- task: SonarQubeAnalyze@4
  displayName: 'SonarQube Analyze'

- task: SonarQubePublish@4
  displayName: 'SonarQube Publish'
  inputs:
    pollingTimeoutSec: '300'

- task: sonar-buildbreaker@8
  displayName: 'SonarQube Build Breaker'
  inputs:
    SonarQube: 'SonarQube-Rideau-PD'

- task: Npm@1
  displayName: 'Build Project'
  inputs:
    command: custom
    customCommand: run build

- task: PublishPipelineArtifact@0
  displayName: 'Publish Artifact'
  inputs:
    artifactName: '$(project)@$(MajorVersion).$(MinorVersion).$(PatchVersion).$(RevisionVersion)'
    targetPath: 'dist'
